# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='tipo_documento',
            field=models.CharField(default='CC', max_length=64, verbose_name='Tipo de Documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('DIRECTOR', 'DIRECTOR'), ('OPERADOR', 'OPERADOR')], max_length=64),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(max_length=64, verbose_name='Numero de Documento'),
        ),
    ]
