# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='direccion',
            field=models.CharField(max_length=64, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(max_length=64, unique=True, verbose_name='N\xfamero de Documento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=64, verbose_name='Tel\xe9fono'),
        ),
    ]
