# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_auto_20161022_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='documento',
            field=models.CharField(max_length=64, unique=True, verbose_name='Numero de Documento'),
        ),
    ]
