# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('codigo', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=64)),
                ('snies', models.CharField(max_length=8)),
                ('creditos', models.IntegerField()),
                ('formacion', models.CharField(max_length=64)),
                ('tipo', models.CharField(max_length=64)),
                ('metodologia', models.CharField(max_length=64)),
                ('titulo', models.CharField(max_length=64)),
            ],
        ),
    ]
