# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-20 02:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='snies',
            field=models.CharField(max_length=8, verbose_name='Registro SNIES'),
        ),
    ]
