# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 19:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0002_auto_20161127_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programa',
            name='descripcion',
            field=models.CharField(max_length=1024, verbose_name='Descripci\xf3n'),
        ),
    ]
