# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0002_auto_20161022_2241'),
        ('programas', '0002_auto_20161020_0259'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Programa',
        ),
    ]
