# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('programas', '0003_delete_programa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Programa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=64)),
                ('snies', models.CharField(max_length=8, verbose_name='Registro SNIES')),
                ('creditos', models.IntegerField()),
                ('formacion', models.CharField(choices=[('PROFESIONAL', 'PROFESIONAL'), ('TECNOLOGICA', 'TECNOLOGICA'), ('TECNICA', 'TECNICA')], max_length=64)),
                ('tipo', models.CharField(choices=[('PREGRADO', 'PREGRADO'), ('POSGRADO', 'POSGRADO')], max_length=64)),
                ('metodologia', models.CharField(choices=[('PRESENCIAL', 'PRESENCIAL'), ('SEMI-PRESENCIAL', 'SEMI-PRESENCIAL'), ('A DISTANCIA', 'A DISTANCIA')], max_length=64)),
                ('titulo', models.CharField(max_length=64)),
            ],
        ),
    ]
