# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-23 05:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0004_programa'),
    ]

    operations = [
        migrations.AddField(
            model_name='programa',
            name='image_url',
            field=models.CharField(default='sda', max_length=256),
            preserve_default=False,
        ),
    ]
