# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 04:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admisiones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_pagado', models.BooleanField(default=False)),
                ('aspirante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admisiones.Aspirante')),
            ],
        ),
    ]
