# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 23:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pago',
            old_name='is_pagado',
            new_name='pagado',
        ),
    ]
