# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-06 02:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('programas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('documento', models.CharField(max_length=64, verbose_name='N\xfamero de Documento')),
                ('tipo_documento', models.CharField(choices=[('CC', 'C\xe9dula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'C\xe9dula de Extranjeria')], max_length=64, verbose_name='Tipo de Documento')),
                ('snp', models.CharField(max_length=64, verbose_name='Icfes SNP')),
                ('puntaje_global', models.IntegerField(verbose_name='Puntaje Global')),
                ('colegio', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Calendario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=512)),
                ('calendario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admisiones.Calendario')),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo', models.IntegerField()),
                ('peso_lectura', models.IntegerField(verbose_name='Peso Lectura Critica')),
                ('peso_matematicas', models.IntegerField(verbose_name='Peso Matematicas')),
                ('peso_naturales', models.IntegerField(verbose_name='Peso Ciencias Naturales')),
                ('peso_sociales', models.IntegerField(verbose_name='Peso Ciencias Sociales')),
                ('peso_ingles', models.IntegerField(verbose_name='Peso Ingles')),
                ('peso_prueba', models.IntegerField(verbose_name='Peso Prueba Espec\xedfica')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=6, unique=True)),
                ('nombre', models.CharField(max_length=64, unique=True)),
                ('puntaje_minimo', models.IntegerField(verbose_name='Puntaje M\xednimo')),
                ('programas', models.ManyToManyField(through='admisiones.Oferta', to='programas.Programa')),
            ],
        ),
        migrations.AddField(
            model_name='oferta',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admisiones.Periodo'),
        ),
        migrations.AddField(
            model_name='oferta',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.Programa'),
        ),
        migrations.AddField(
            model_name='calendario',
            name='periodo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admisiones.Periodo'),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admisiones.Oferta'),
        ),
    ]
