# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 22:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('admisiones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aspirante',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='aspirante',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='periodo',
        ),
        migrations.RemoveField(
            model_name='oferta',
            name='programa',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='programas',
        ),
        migrations.DeleteModel(
            name='Aspirante',
        ),
        migrations.DeleteModel(
            name='Oferta',
        ),
    ]
