# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='activo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='periodo',
            name='hay_resultados',
            field=models.BooleanField(default=False),
        ),
    ]
