# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 22:43
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('programas', '0004_programa'),
        ('admisiones', '0002_auto_20161022_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aspirante',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('documento', models.CharField(max_length=64, verbose_name='Numero de Documento')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cedula de Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cedula de Extranjeria')], max_length=64, verbose_name='Tipo de Documento')),
                ('snp', models.CharField(max_length=64, verbose_name='Icfes SNP')),
                ('puntaje_global', models.IntegerField(verbose_name='Puntaje Global')),
                ('colegio', models.CharField(max_length=64)),
                ('nombre', models.CharField(max_length=64)),
                ('apellido', models.CharField(max_length=64)),
                ('direccion', models.CharField(max_length=64)),
                ('telefono', models.CharField(max_length=64)),
            ],
            options={
                'abstract': False,
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo', models.IntegerField()),
                ('peso_lectura', models.IntegerField()),
                ('peso_matematicas', models.IntegerField()),
                ('peso_naturales', models.IntegerField()),
                ('peso_sociales', models.IntegerField()),
                ('peso_ingles', models.IntegerField()),
                ('peso_prueba', models.IntegerField()),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admisiones.Periodo')),
                ('programa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programas.Programa')),
            ],
        ),
        migrations.AddField(
            model_name='aspirante',
            name='programa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admisiones.Oferta'),
        ),
    ]
