# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0003_aspirante_ponderado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='ponderado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
