# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-22 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programas', '0004_programa'),
        ('admisiones', '0003_auto_20161022_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodo',
            name='programas',
            field=models.ManyToManyField(through='admisiones.Oferta', to='programas.Programa'),
        ),
    ]
