# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 23:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0004_auto_20161113_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='hay_resultados',
            field=models.BooleanField(default=False, verbose_name='Resultados'),
        ),
    ]
