# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-27 19:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0007_remove_aspirante_fecha_inscripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='aspirante',
            name='admitido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='aspirante',
            name='nota_admision',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='direccion',
            field=models.CharField(max_length=64, verbose_name='Direcci\xf3n'),
        ),
        migrations.AlterField(
            model_name='aspirante',
            name='telefono',
            field=models.CharField(max_length=64, verbose_name='Tel\xe9fono'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='peso_lectura',
            field=models.IntegerField(verbose_name='Peso Lectura Cr\xedtica'),
        ),
        migrations.AlterField(
            model_name='oferta',
            name='peso_matematicas',
            field=models.IntegerField(verbose_name='Peso Matem\xe1ticas'),
        ),
    ]
