# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 13:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admisiones', '0008_auto_20161127_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aspirante',
            name='nota_admision',
            field=models.CharField(default='', max_length=128, verbose_name='Nota Admisi\xf3n'),
        ),
    ]
